### ISSUE TITLE
Can't see the flag in chrome on LUbuntu 20?

### ISSUE THREAD

**Issue by JiaoXianjun** [rms-support-letter/rms-support-letter.github.io#2193] opened 2021-03-25 19:32 UTC
Hello,

I can see the flags in firefox on Ubuntu and with my iPhone chrome, but not in the chrome on Ubuntu. My chrome on Ubuntu is like this:
![screen](https://user-images.githubusercontent.com/5212105/112532547-3b5ef380-8da9-11eb-90a1-0abe010f4990.jpg)

**Comment by imachug** [comment] 2021-03-25 19:44
The site uses emojis. Perhaps something's wrong with fonts.

**Comment by cmd410** [comment] 2021-03-25 19:44
![](https://user-images.githubusercontent.com/48290258/112533902-808c2100-8dbb-11eb-860c-c1bd9b0bab76.png)

Wait, there are supposed to be flags..?

**Comment by cmd410** [comment] 2021-03-25 19:44
Windows 10, Mozilla. Same problem.

**Comment by RealJTG** [comment] 2021-03-25 19:44
Hehe, the reverse side of emojis. 
Mb we should include emoji webfont like https://cdnjs.com/libraries/emojione or https://github.com/googlefonts/noto-emoji?

@JiaoXianjun try `sudo apt install fonts-noto-color-emoji`

**Comment by shenlebantongying** [comment] 2021-03-25 19:44
yes..........

![image](https://user-images.githubusercontent.com/20123683/112534059-06d74180-8d81-11eb-91c5-c9dd27060ab7.png)

**Comment by shenlebantongying** [comment] 2021-03-25 20:38
I think we better add a font that contains emoji for those flags.

A few distro's default font config doesn't have it.............

Since this going to be access from people all over the world, we should add it directly to the repo.

**Comment by shenlebantongying** [comment] 2021-03-25 20:41
Or, we add some svg pictures of those flags?

**Comment by JiaoXianjun** [comment] 2021-03-25 20:49
> sudo apt install fonts-noto-color-emoji

sudo apt install fonts-noto-color-emoji -- it works for me: chrome on Ubuntu (mine is LUbuntu)

**Comment by nukeop** [comment] 2021-03-25 21:50
Do you guys know how to link the emoji font in Jekyll without using a cdn? Can anyone open a pull request?

**Comment by RealJTG** [comment] 2021-03-25 22:39
Although I've never used Jekyll before, there is https://github.com/jekyll/jemoji plugin, this probably will require replacing raw emojis with github placeholders like :us: -> `:us:`

**Comment by RealJTG** [comment] 2021-03-25 23:28
```diff
diff --git a/_config.yml b/_config.yml
index 2e15f6a4..fd85e2eb 100644
--- a/_config.yml
+++ b/_config.yml
@@ -8,6 +8,9 @@ repository: rms-support-letter/rms-support-letter.github.io
 # Build settings
 theme: minima
 
+plugins:
+  - jemoji
+
 exclude:
   - .sass-cache/
   - .jekyll-cache/
```

```diff
diff --git a/_sass/custom.scss b/_sass/custom.scss
index f73e2ff4..21994c52 100644
--- a/_sass/custom.scss
+++ b/_sass/custom.scss
@@ -4,4 +4,9 @@
 
 .translation {
   font-size: 2em;
+}
+
+.translation .emoji {
+       width: 40px;
+       height: 40px;
 }
```

```diff
diff --git a/_layouts/signed.html b/_layouts/signed.html
index aa9d2e6f..9bb5fda7 100644
--- a/_layouts/signed.html
+++ b/_layouts/signed.html
@@ -6,20 +6,20 @@ layout: home
 
 <div class="translations">
   <p>Translations:</p>
-  <a class="translation" href='/'>🇺🇸</a>
-  <a class="translation" href='/index_zh_cn.html'>🇨🇳</a>
-  <a class="translation" href='/index_tr.html'>🇹🇷</a>
-  <a class="translation" href='/index_ro.html'>🇷🇴</a>
-  <a class="translation" href='/index_es.html'>🇪🇸</a>
-  <a class="translation" href='/index_pt_br.html'>🇧🇷</a>
-  <a class="translation" href='/index_de.html'>🇩🇪</a>
-  <a class="translation" href='/index_fr.html'>🇫🇷</a>
-  <a class="translation" href='/index_pl.html'>🇵🇱</a>
-  <a class="translation" href='/index_it.html'>🇮🇹</a>
-  <a class="translation" href='/index_ko.html'>🇰🇷</a>
-  <a class="translation" href='/index_ru.html'>🇷🇺</a>
-  <a class="translation" href='/index_fa.html'>🇮🇷</a>
-  <a class="translation" href='/index_ua.html'>🇺🇦</a>
+  <a class="translation" href='/'>:us:</a>
+  <a class="translation" href='/index_zh_cn.html'>:cn:</a>
+  <a class="translation" href='/index_tr.html'>:tr:</a>
+  <a class="translation" href='/index_ro.html'>:romania:</a>
+  <a class="translation" href='/index_es.html'>:es:</a>
+  <a class="translation" href='/index_pt_br.html'>:brazil:</a>
+  <a class="translation" href='/index_de.html'>:de:</a>
+  <a class="translation" href='/index_fr.html'>:fr:</a>
+  <a class="translation" href='/index_pl.html'>:poland:</a>
+  <a class="translation" href='/index_it.html'>:it:</a>
+  <a class="translation" href='/index_ko.html'>:kr:</a>
+  <a class="translation" href='/index_ru.html'>:ru:</a>
+  <a class="translation" href='/index_fa.html'>:iran:</a>
+  <a class="translation" href='/index_ua.html'>:ukraine:</a>
 </div>
```

Works, I guess. @nukeop what do you think?

---

Before:

![2021-03-26-012020_792x328_scrot](https://user-images.githubusercontent.com/930399/112555953-dec3fe80-8dd1-11eb-8e21-6117f0d63211.png)


After:

![2021-03-26-012549_773x342_scrot](https://user-images.githubusercontent.com/930399/112556204-598d1980-8dd2-11eb-971b-8f8708e09ff0.png)

**Comment by shenlebantongying** [comment] 2021-03-25 23:32
GitHub only support a very small set of plugins, and we have to rebuild the site locally then reupload for every new PR. Its might be a big burden somehow, just my 2 cents
https://docs.github.com/en/github/working-with-github-pages/about-github-pages-and-jekyll#plugins

**Comment by RealJTG** [comment] 2021-03-26 13:52
On some Windows systems there may be even worse cases when country flag emojis are rendered as "tofu", without fallback and readable country codes

![200279100016_17706](https://user-images.githubusercontent.com/930399/112641563-2a66be80-8e4b-11eb-961b-2e45f2339043.jpg)

**Comment by RealJTG** [comment] 2021-03-26 19:48
Hey, after https://github.com/rms-support-letter/rms-support-letter.github.io/commit/20040b618b6f0d018261b54ea93e77bb8af728aa I see no more way to use jemoji plugin for GitHub-style emojis coz flags now are assembled automatically from locale codes but GitHub-style flag emoji names sometimes differs from locale codes:

🇪 +  🇸 = 🇪🇸 
`:es:` = :es:

but

🇧 + 🇷 = 🇧🇷 
`:br:` = :br:
`:brazil:` = :brazil:


So after  https://github.com/rms-support-letter/rms-support-letter.github.io/commit/20040b618b6f0d018261b54ea93e77bb8af728aa there's simply no more place where 🇧🇷  could be replaced with `:brazil:` if we want to render emojis as images.

**Comment by imachug** [comment] 2021-03-26 19:50
Maybe we could use an emoji font instead?

**Comment by cmd410** [comment] 2021-03-26 19:59
Maybe, optionally check for emoji attribute in translation and if it exists, use it.

**Comment by RealJTG** [comment] 2021-03-26 20:02
@cmd410 that's confusing IMO. 
20040b618b6f0d018261b54ea93e77bb8af728aa makes translation easier, so I'm closing #2717 in favor of web fonts, someone please pick this issue.

**Comment by imachug** [comment] 2021-03-26 20:44
Can someone from this issue please check if https://rms-support-letter.github.io/ shows the flags for them now or not?

**Comment by shenlebantongying** [comment] 2021-03-26 20:54
@imachug 
It works, (even works when disable javascrip too).

However, does it is intended that the font was loaded twice and one of them is 9 Mb..........

I have no idea about fonts, but unless someone else propose a better solution, i think its ok.

![image](https://user-images.githubusercontent.com/20123683/112691519-d3191c00-8e53-11eb-894b-3b9bcb41637e.png)

**Comment by imachug** [comment] 2021-03-26 20:59
I *think* the second load was caused by the devtools themselves but I'm not sure

**Comment by shenlebantongying** [comment] 2021-03-27 01:08
@imachug  I think he or she just solved the size problem
https://github.com/rms-support-letter/rms-support-letter.github.io/pull/3240

**Comment by imachug** [comment] 2021-03-27 14:43
Closing because we appear to have resolved the issue.

**Closed by imachug** 2021-03-27 14:43 UTC

**Comment by JiaoXianjun** [comment] 2021-03-27 14:49
> Closing because we appear to have resolved the issue.

When will the change take effect? Currently at the top there is still nothing about the number.

![image](https://user-images.githubusercontent.com/5212105/112724513-1044e300-8f14-11eb-8498-924b37d95694.png)
