### ISSUE TITLE
Mail spam

### ISSUE THREAD

**Issue by luukasahola** [rms-support-letter/rms-support-letter.github.io#6450] opened 2021-04-07 20:11 UTC
Hey everyone,

As many of you have noticed, you've gotten an email regarding a poll "for a support letter for Galla Mancheva and Susanne Eiswirt". Although it might actually look legitimate, it isn't. I haven't dealt with the FSF ever and especially not with FSFE, so it's almost certainly a spam email. The data was most likely scraped from the letter itself and checked against the email addresses for our GitHub accounts. **Don't click any links in the email**, as the links might run tracking scripts on your device.

**Comment by checooh** [comment] 2021-04-07 20:27
For me it seems legit. The issue is real, the voting site seems to be also real (it claims to be somehow affiliated with Cornell University, the "donate" link leads to Cornell University website which mentions the "CIVS voting system"). The link seems to be somehow strange ("civs1.civs.us"), but both the civs1.civs.us and civs.cs.cornell.edu are resolved to the same IP address.

**Comment by luukasahola** [comment] 2021-04-07 20:35
Alright, the email seems to look legitimate while I went through it further. I still have quite a concern, mainly when talking about how the email addresses were acquired. The targeting of the email also raised concerns for me, as signature data is being scraped by the opponents of this letter even at the moment.

**Comment by 6r1d** [comment] 2021-04-07 20:36
@nukeop , what do you think? I certainly don't know about this email, but people in support letter left a `mailto:`, even if I recommended to use sites or other profiles.

@lukacovicadam what is this letter about, anyway?

> The issue is real, the voting site seems to be also real

So what's happening, @checooh ?

> it claims to be

Not enough to prove an identity yet.

> the "donate" link leads to Cornell University website

Anyone can do that so far...

> The link from the letter seems to be somehow strange

Uh-oh.

> both the civs1.civs.us and civs.cs.cornell.edu are resolved to the same IP address
> WHOIS of the IP address gives "Organization: Cornell University (CORNEL)"

It's interesting that instead of proving of who they are they need others to do that. Ok, let's discuss what's up.

**Comment by checooh** [comment] 2021-04-07 20:42
Yes, I also think that that's strange to just grab addresses and spam without even creating a discussion here. I have asked the poll author on email, waiting to see what they will answer.

>>the "donate" link leads to Cornell University website
>Anyone can do that so far...
Not just this, the Cornell University website links the voting service back (http://www.cs.cornell.edu/andru/donate.html). Of course, they potentially could be hacked so I don't know, honestly.

**Comment by JoonasC** [comment] 2021-04-07 20:43
Well, guess this is what I get for signing with my real github account.

**Comment by 6r1d** [comment] 2021-04-07 20:46
> Well, guess this is what I get for signing with my real github account.

Good time to hide an email to protect yourself from spam, for sure.
The point was to show we're real people who want to protect RMS, because the other side did just that, except they did not support RMS.

**Comment by JoonasC** [comment] 2021-04-07 20:46
Who knows we might already be placed on some industry blacklist, taking into account the number of companies that signed the opposing letter. Though that is a risk I was willing to take when signing this letter.

**Comment by 6r1d** [comment] 2021-04-07 20:54
> Who knows we might already be placed on some industry blacklist, taking into account the number of companies that signed the opposing letter. Though that is a risk I was (and still am) willing to take when signing this letter.

First of all, this "blacklist" is a big farce. If someone "blacklists" others for **thinking** and speaking their mind, well, you know, everyone did at some point.

Then again, if someone will do just that, it's a win-win. Would you want to work for people who tell you what opinions you should have to keep working with them?

**Comment by JoonasC** [comment] 2021-04-07 20:54
Did any of you get another letter, this time apparently for a poll about "debian defending nazis".
IMHO, these emails seem malicious, and shouldn't be treated as legitimate.

**Comment by 6r1d** [comment] 2021-04-07 20:55
> IMHO, these emails seem malicious, and shouldn't be treated as legitimate.

I think their mailing list is filled with spam. Moderating mailing lists isn't easy.

**Comment by luukasahola** [comment] 2021-04-07 20:59
Same Cornell Email address. Yup, definitely malicious.

**Comment by checooh** [comment] 2021-04-07 21:18
>Who knows we might already be placed on some industry blacklist

I don't think so. By just signing this letter you don't even break the Contributor's Covenant. Actually, I want to try and get Outreachy internship somewhere around next year and the outcome will tell.

>Did any of you get another letter, this time apparently for a poll about "debian defending nazis".

Yes, got this also. Seems that everyone can create a poll there. I just did that without any problems using my testing emails.

>Same Cornell Email address. Yup, definitely malicious.

The actual poll author's email is in the letter itself.

I'm not pushing anyone to that though. Can't deny that all this looks dodgy.

**Comment by martinge17** [comment] 2021-04-07 21:39
Same emails here.

**Comment by ic-scm** [comment] 2021-04-07 21:44
I also received those e-mails, even without my e-mail address in the signature. I had my e-mail address on my github profile, but I removed it a few months ago due to job offer spam.

**Comment by aleferri** [comment] 2021-04-07 21:49
No one noted that the proponent is adolfhitler@netc.eu?
This sick troll could use medical treatment immediatly.

**Comment by JoonasC** [comment] 2021-04-07 21:51
Maybe some Cornell university student or faculty member signed up people from this letter to their CIVS mailing list?

**Comment by checooh** [comment] 2021-04-07 22:04
@BASM 
>M -- is Meritocracy.

I guess, the aim here to expose the FSFE's dirty laundry.  Why is it done like this? Don't know. Maybe they want to stay anonymous, maybe it's just some weird provocation.

@ic-scm 
>I also received those e-mails, even without my e-mail address in the signature. 

>without my e-mail address in the signature

Ouch! Now that's concerning. Your profile links a website which contains the email contact. Does it redirect mail to your personal address?

@JoonasC 
>Maybe some Cornell university student or faculty member signed up people from this letter to their CIVS mailing list?

No. The service seems to be created by one of the Cornell University staff members, but in fact, anyone can create a poll there.
![Screenshot_20210408_010106](https://user-images.githubusercontent.com/521557/113940412-f09f9b80-97ec-11eb-8359-09b824fef142.png)

**Comment by JoonasC** [comment] 2021-04-07 22:08
@checooh Yes, anyone can create a poll on civs, but that doesn't explain how email addresses of people on this letter got into tgeir mailing list.

**Comment by nukeop** [comment] 2021-04-07 22:15
You can use their website to stop receiving further spam. I got two of those so far, just ignored them.

**Comment by nukeop** [comment] 2021-04-07 22:16
> Who knows we might already be placed on some industry blacklist, taking into account the number of companies that signed the opposing letter. Though that is a risk I was (and still am) willing to take when signing this letter.

Stop spreading this FUD. Nobody is being placed on any blacklists. Anybody spreading this lie wants you to be scared for being right.

**Comment by mjg59** [comment] 2021-04-07 22:22
These mails are likely to be from @dpocock, the owner of fsfellowship.eu. He has previously the CIVS service to harass members of the free software community, and one of the most recent posts on his debian.community blog accuses Debian members of being fascists.

**Comment by ic-scm** [comment] 2021-04-07 22:22
@checooh No, those are two completely different e-mail addresses.

**Comment by JoonasC** [comment] 2021-04-07 22:23
@nukeop I wasn't stating as fact that anyone is placed on a blacklist. Sorry.

**Comment by dpocock** [comment] 2021-04-07 22:25
@mjg59 is spreading defamation, wasting time and wasting people's energy.  He appears on mailing lists every day making false accusations against Jacob Appelbaum.

**Comment by mjg59** [comment] 2021-04-07 22:28
(Another of @dpocock's traits here is to avoid actually denying anything)

**Comment by dpocock** [comment] 2021-04-07 22:30
There are many sites to verify the story of these women

https://twitter.com/malinagalina

Censored / flagged by Hacker News:
https://news.ycombinator.com/item?id=25494205

https://www.reddit.com/r/programming/comments/kgzcv7/i_took_fsf_europe_to_court/

https://flameeyes.blog/2020/12/22/i-no-longer-support-fsfe/

https://flameeyes.blog/2021/02/16/my-take-on-what-i-would-replace-fsfe-with/

Some people are quitting FSF because of the current crisis.  It would be a disaster if they give their money to FSFE, the FSFE is so much worse than anything people said about RMS.

**Comment by checooh** [comment] 2021-04-07 22:31
@JoonasC 
> that doesn't explain how email addresses of people on this letter got into their mailing list.

Well, @ic-scm reports: 

>I had my e-mail address on my github profile, but I removed it a few months ago due to job offer spam.

So either it is some manual digging, or someone has a dump of github user email addresses on their hands.

@dpocock maybe you could tell us something about the subject emails?

**Comment by ic-scm** [comment] 2021-04-07 22:35
Oh, I forgot that my e-mail address is also in most git commits, I guess it's possible that they just cloned repositories of some users.

**Comment by checooh** [comment] 2021-04-07 22:42
>Oh, I forgot that my e-mail address is also in most git commits, I guess it's possible that they just cloned repositories of some users.

Yeah, that could explain it. Someone has harvested the addresses from this repo's commits.

**Comment by dpocock** [comment] 2021-04-07 22:45
Running an open letter / petition through Github was somebody else's idea.  Don't blame the trolls, blame the person who started the original repository.

Debian is currently having the vote to vilify Dr Stallman.  By doing that vote, Debian is inciting every troll to come out of their cave and be part of the moment.

No matter how Debian votes and no matter how many trolls participate, I suspect it will make little difference to the decisions RMS makes next.  Everybody will simply suffer the side effects and regrets about exposing their email addresses.

Every puppet organization like FSFE that is slandering Dr Stallman is a troll too.  It isn't fair to criticize the anonymous trolls when these massive sock puppets are preaching in broad daylight, taking booths at conferences, giving talks where they pretend to be our leaders.

**Comment by nukeop** [comment] 2021-04-07 22:45
I also suspect this "debian community" guy, he is a bit of a spammer/crazy person.

**Comment by nukeop** [comment] 2021-04-07 22:56
https://lwn.net/Articles/814508/

Looks like he's been going after Debian people for some time now

**Comment by ohsix** [comment] 2021-04-07 22:58
> Every puppet organization like FSFE that is slandering Dr Stallman is a troll too. It isn't fair to criticize the anonymous trolls when these massive sock puppets are preaching in broad daylight, taking booths at conferences, giving talks where they pretend to be our leaders.

slander is bad, lets have less slander. maybe we can start with not imagining a big group of people that are completely homogenous with certain ideas but also an unyielding desire to persecute the people we like

that might make us feel more important than we are. it's more likely that we're just having one long extended public meltdown and the new people need to get up to speed

**Comment by dpocock** [comment] 2021-04-07 23:00
The accusations from certain people at Debian are defamation.  They attacked me after my father died.  Every other organization treated my family with respect.  Rogue elements of Debian attacked me.  The same people are attacking Dr Stallman and other volunteers.

**Comment by ohsix** [comment] 2021-04-07 23:02
> The same people are attacking Dr Stallman and other volunteers.

isn't it handy that you have this thing in the public imagination to use for turning your personal grief crank?

**Comment by nukeop** [comment] 2021-04-07 23:07
@dpocock 
Confirm or deny: did you create those polls on CIVS and add people signing our letter to them without their knowledge or consent?

**Comment by ic-scm** [comment] 2021-04-07 23:19
> > Oh, I forgot that my e-mail address is also in most git commits, I guess it's possible that they just cloned repositories of some users.
> 
> Yeah, that could explain it. Someone can harvest the addresses from this repo's commits and hiding the contacts in the profile won't help against it.

I'm pretty sure my commit here was made with the obfuscated github address, so they probably had to clone my other repositories

**Comment by nekonee** [comment] 2021-04-07 23:25
@dpocock I wish you'd remove my email from your spam list. If your goal was to make a better environment for women in free software community... congrats, because you've just made one scared.

**Comment by aleferri** [comment] 2021-04-08 00:27
@dpocock If you felt you were mistreated by "some rogue elements of Debian" i feel sorry for you. Yet two wrongs do not make a right, sever your ties with Debian and go ahead, state your dissatisfaction in a civil way, make a blog, write an essay, paint, then forgive everyone and start another, more interesting project. Don't waste your and everyone else life with trolling and spamming. Please.

**Comment by dpocock** [comment] 2021-04-08 06:14
> isn't it handy that you have this thing in the public imagination to use for turning your personal grief crank?

This is not a "personal grief crank", this is simply an example of the very low standards being set by many people in and around Debian.  No organization attacks a volunteer at such a time but they troll me with various written attacks.

Please go up to each Debian Developer and ask them to confirm or deny if they are one of the trolls.  I am definitely not responsible for these problems.

FSFE even published a blog attacking FSF.  FSFE attacking FSF.  If that isn't trolling, what is?
https://fsfe.org/news/2021/news-20210324-01.en.html

**Comment by mjg59** [comment] 2021-04-08 07:02
@dpocock When you say "I am definitely not responsible for these problems", that sounds awfully like "I sent these mails, but it wasn't my fault".

**Comment by emestee** [comment] 2021-04-08 07:09
@dpocock did you or did you not collect email addresses from both repositories and signed them up for a vote?

**Comment by nukeop** [comment] 2021-04-08 07:23
@dpocock Answer my question

**Comment by iromeister** [comment] 2021-04-08 10:54
> No one noted that the proponent is [adolfhitler@netc.eu](mailto:adolfhitler@netc.eu)?

That email account got blocked - I asked the provider.

**Comment by cmpunches** [comment] 2021-04-08 17:31
I think several members of our community here are a little blind to an opportunity to expose a lack of justice for someone else who was targeted in these communities, in this case by the same people behind the anti-stallman letter we're all here to address.

Daniel's been trying to tell people for what looks like a couple years now that he was a previous smear target of MDB.  I didn't know who she was until I searched the name in my email inbox and found him before any of this coming out telling people about her smear campaign against him.

Now here we are addressing her smear campaign about someone else, while flaming someone else who has repeatedly try to step out.

I was targeted by some folks associated with the gnome foundation about 10 years back and found similar reactions to what I'm seeing towards Mr. Pocock, here, and I don't think it's appropriate.

Malignant narcissists commonly bait and smear their targets with impunity to the point that their enraged target will react and then that reaction is socialized as the justification for the targeting.

Does Daniel have to be RMS for it to be wrong?  Did I?

**Comment by aleferri** [comment] 2021-04-08 18:34
Exposing lack of justice and campaigning for it is all good to me. Unauthorized use of email addresses to force everyone to partecipate in other discussions with low effort spam is not.
If you wish to support the two women who were discriminated against by the FSFE or remove the ban to daniel pockock from Debian take some effort to write and setup a well worded written letter. At this point promote the issue on forums/twitter/reddit/etc. Please, think of the numbers: everyday there are milions of issues. What if everyone engage in low effort spam to gather supporters?
This is exactly the kind of spam self appointed paladins of no one vomit on unsuspecting victims that are so shortsighed to engage in conversation with them. If an issue is important to you don't troll or spam. Prepare material to cover your position and take high effort actions that can convince me that your issue is important enought to justify the use of my time to support you or your ideas/efforts.
You have here an example of high effort: prepare an infrastucture, take the time to write an open letter and dedicate your time to overview the whole thing until it is complete.
As software engineers in free software we know that no one wants to waste time in depending on/learning to use throw away code of someone else.

**Comment by LegoLivesMatter** [comment] 2021-04-08 18:47
I got these emails as well

**Comment by checooh** [comment] 2021-04-08 18:55
I'm in no position to decide, but I am pretty sure that anyone here would support a good cause. The problem is that what happened here doesn't look like one, and worse, it looks like the opposite of a good cause. Nobody has come here and created a discussion "Guys, look, here are another cases of smearing people, please support". Our e-mail addresses were scraped without our consent (and it had to be the custom script to do that) and we got a bunch of spam out of the blue (with adolfhitler as a contact email, ha-ha, funny!). Then @dpocock comes here, writes incoherent messages and refuses to give direct answers to our direct questions. That's plain creepy, no wonder the people are distrusting. You can see that at first, I was defending these emails, telling people that it's not a spam. I was trying to be objective, but now I regret that. I feel like an accomplice to some trolling.
I second @aleferri. You should prepare a nice open letter, provide people the details of what happened to you and Daniel, and it will be something that we could discuss and support.

**Comment by 6r1d** [comment] 2021-04-08 19:10
> Does Daniel have to be RMS for it to be wrong? Did I?

Nope, Chris, social status exists but isn't involved directly. The problem is in approach to public emailing.

> Daniel's been trying to tell people for what looks like a couple years now that he was a previous smear target of MDB. I didn't know who she was until I searched her name in my email inbox and found Daniel trying to expose this ahead of time, a couple years before any of this anti-stallman business happening, telling people about her smear campaign against him.

Oh. So that's what was happening all this time. **You're the first guy to explain it properly, so I can understand.**
Thank you.

> I second @aleferri. You should prepare a nice open letter, provide people the details of what happened to you and Daniel, and it will be something that we could discuss and support.

Agreed. Add links to internet Archive. Try to stand neutral and professional, but point out what is wrong. Keep it short, but link all related evidence.

----

For the context, that is what Bryan Lunduke is doing right now. He's communicating with representatives of many companies in open letter by email to explain the witch hunt we have now isn't very nice or healthy.

**Comment by dpocock** [comment] 2021-04-08 20:04
The first organization to run these polls was the FSFE.  They had a poll and people voted for me:

https://civs.cs.cornell.edu/cgi-bin/results.pl?id=E_29119d29f759bbf8

That is when the FSFE in Berlin started the conspiracy with @mollydb to spread rumors in her whispering networks.  That is the term she uses in her FOSDEM 2019 talk.  They were unhappy with the result of the election so everywhere they go they start asking these questions "are you one of the trolls?"  Notice three people asked the same question consecutively today in this thread but not one provided any evidence.  Take a good look, that is how they work.

If your boss or your spouse asks you a question, it is important to answer honestly.  But the people running around asking these questions in mailing lists don't pay us.  None of us are obliged to answer a question from somebody with a big title in Debian or Fedora.  If they claim to represent us, they should be answering our questions, for example, @mollydb - how much money have you received from each free software organization for your travel?  People donated that money because of the work done by the developers and then it pays for the leader's girlfriend to travel to a conference.  I sometimes had to wait more than a year to get my expenses back from Debian but some people appear to travel every month without writing code.

**Comment by franpoli** [comment] 2021-04-08 20:10
We cannot take a position on a case we do not know the ins and outs. [According to Matthias Kirschner, the Executive Council President of FSFE](https://mastodon.social/@kirschner/106024329141224066), they put in place a [Central CARE Team](https://fsfe.org/about/codeofconduct.en.html) which is supposed to assist on [discrimination and sexism questions](https://chaos.social/@carl/106023795271612377). Complaints about the Care Team itself need to be addressed by the President of the Executive Team. It is interesting to note that some members of the Care Team are also members of the Executive Team.  They are both judge and jury.

**Comment by dpocock** [comment] 2021-04-08 20:13
> and it had to be the custom script to do that

it is a one liner that works for any Git repository

```
git log | grep ^Author: | cut -f2- -d: | sort -u
```

Use it wisely

I'm granting you a license to use that script under the GPL v3 or greater

**Comment by dpocock** [comment] 2021-04-08 20:17
> We cannot take a position on a case we do not know the ins and outs. [According to Matthias Kirschner, the Executive Council President of FSFE](https://mastodon.social/@kirschner/106024329141224066), they put in place a [Central CARE Team](https://fsfe.org/about/codeofconduct.en.html) which is supposed to assist on [discrimination and sexism questions](https://chaos.social/@carl/106023795271612377). Complaints about the Care Team itself need to be addressed by the President of the Executive Team. It is interesting to note that members of the Care Team can be members of the Executive Team. They are both judge and jury.

Actually, the fellowship representatives were

- volunteers
- elected by the community

So the fellowship representatives don't answer to the Executive Committee.  I answer to the people who pay me.  Fellows donate money to FSFE so they have to answer us, we set the rules for them.

**Comment by checooh** [comment] 2021-04-08 20:50
I guess, the message containing the one-liner for extracting the email addresses was deleted to not provide spammers an easy way. I have tried it, and yes, it gives the e-mail addresses of all the contributors. Turns out I was wrong about the custom script. But this was the minor issue and the other issues still stand.

>Notice three people asked the same question consecutively today in this thread but not one provided any evidence. Take a good look, that is how they work.

This is how _all_ people work! If you act in a creepy way, the people _will be_ creeped out and they _will be_ asking questions, like "WTF?" 
We here are not refusing to help you, but we are not familiar with the events that happened to you, that's why we need a _proper detailed explanation_.

**Comment by dpocock** [comment] 2021-04-08 21:16
> We here are not refusing to help you, but we are not familiar with the events that happened to you, that's why we need a _proper detailed explanation_.

I lost two family members in less than a year.  I resigned from some of my voluntary roles.  At such a time, it is completely inappropriate to either demand explanations or make accusations from any volunteer.  I have been doing voluntary work with free software for over 25 years.

Moreover, when I resigned from FSFE, I resigned due to the fact that the organization and the president were so completely hopeless.  I do not see any way to fix that organization.  If I have one hour free to do something as a volunteer, I would give that time to any other organization but not FSFE.  So I resigned.  A resignation is not evidence of wrongdoing.  Many people have resigned from FSFE because the problem is in the organization.  For some people, it is like leaving a cult.
https://fsfellowship.eu/fsfe-resignations-and-expulsions/

People who have never been an employee of Debian, Fedora or FSFE have no obligation to give explanations or follow orders from the former leader's girlfriend.

**Comment by 6r1d** [comment] 2021-04-08 21:27
> I lost two family members in less than a year.

I'm sorry to hear that

> I resigned from some of my voluntary roles. At such a time, it is completely inappropriate to either demand explanations or make accusations against any volunteer. I have been doing voluntary work with free software for over 25 years.

It's a volounteer work, you have a right to leave.

At this point, I don't understand the whole story, but at least I was able to tell that.

**Comment by nukeop** [comment] 2021-04-08 21:27
@dpocock You either answer me if you spammed our signatories or you're getting banned from this repo.

**Comment by dpocock** [comment] 2021-04-08 21:32
Please don't send threats to volunteers, especially when it is 11:30pm in my time zone

Why are you sending this threat to me personally?  Why don't you send the same questions and threats to everybody on the Internet?  Anybody can come to github and clone a repository.  Even if you ban somebody, they can still clone the repository.

Setting up petitions in Github was the brilliant idea of @mollydb - please save your concern for her.

**Comment by nukeop** [comment] 2021-04-08 21:34
Ok, you keep avoiding the question, you're getting a 24h timeout. Come back when you're ready to answer.

**Comment by nukeop** [comment] 2021-04-08 21:48
We know who did it and how, the best course of action is to ignore it for now. If anything else comes up, please reopen this or create a new issue (hopefully it won't)

**Closed by nukeop** 2021-04-08 21:48 UTC

**Comment by DebianCommunity** [comment] 2021-04-08 22:35
@nukeop is now behaving like the @mollydb lynch mob

> We know who did it and how

You just made that up.

That is really disappointing.

This repository was created as an alternative to mob culture.  The accusations in this thread are just as sinister as @mollydb falsifying accusations against Dr Stallman.  This repository just lost all credibility.

**Comment by nukeop** [comment] 2021-04-08 22:41
For the record, the above is the same guy's alt account.

**Comment by cmpunches** [comment] 2021-04-08 22:47
I would have to agree that there are some epistemological failures there, but I wouldn't call it so dramatic a thing that the support effort "lost all credibility".   

He was right to mute you while you're refusing to answer questions, and you were right to refuse to answer them after initially saying that you were not responsible for the emails.  If there is anything I've learned well over the years it's that often being right has more consequences than being wrong.

I do not think he was right to accuse you though without evidence.  I just don't see the logic behind the belief.  I've seen no evidence that this was you.

If you could please put the accusation to rest by being more clear in saying whether you sent the emails, that's the best we can all hope for.

**Comment by nukeop** [comment] 2021-04-08 22:57
Since I take this kind of abuse of trust very seriously, and he's spammed not only our contributors but also the contributors of rms-open-letter, I have reported his accounts to Github support detailing his recent actions.

**Comment by Jan200101** [comment] 2021-04-09 13:17
Glad to hear I am not the only one receiving these.
I suggest to those that have no interest in ever voting on that service to stop future emails from sending
https://civs1.civs.us/cgi-bin/mail_mgmt.pl

**Comment by nukeop** [comment] 2021-04-09 23:23
Another day, another spam mail from Pocock:

```
A Condorcet Internet Voting Service poll named Molly / Stallman role reversal puzzle has been created. You have been designated as a voter by the poll supervisor, Cindy Rogers (talking.is.better@francemel.fr).

Description of poll: If the FSF founder was a woman and an angry male employee who left two years ago was running around starting petitions against that woman, do you believe Github and the police would be more likely to classify it as stalking and shut down the vendetta?
```

**Comment by cmpunches** [comment] 2021-04-09 23:28
I apologize for inadvertantly enabling the disruption.  I really feel for the guy and his story, and leave a standing offer to try to help him be heard when he's no longer doing things like this.

**Comment by checooh** [comment] 2021-04-10 02:06
Well, it seems we actually don't know much. One one hand, Pocock's behavior is... dodgy. On the other hand, we don't know for sure who is actually behind these polls. Suspicions on Pocock began when Matthew Garrett, who is one of the core signatories of the opposing letter, came here first, pointed to Pocock and summoned him with @ mention. And it may very well be Pocock, but it also could be someone who is trying to frame him. I believe, the best course of action for now would be to just ignore the letters without blaming anybody.
Maybe @cmpunches should make some descriptions of what happened to him and to Pocock, so we would at least have some consistent material to look at? If community is interested, of course.

**Comment by nukeop** [comment] 2021-04-10 21:10
![Screenshot_2021-04-10 (5) Spam alsw protonmail com ProtonMail](https://user-images.githubusercontent.com/12746779/114284683-32288480-9a41-11eb-9106-cfc1dfa3c70f.png)

Another email from our buddy @dpocock

**Comment by hatkidchan** [comment] 2021-04-10 21:12
Well, I've just got that email too, also I've signed in letter. Does it means they're using that letter as list of emails to spam into?
Actually, I've got it twice (one @ April, 7 and one just now). Should we mark them as spam or something?

**Comment by cmpunches** [comment] 2021-04-10 21:14
One idea I had was reading what he had to say.

**Comment by nukeop** [comment] 2021-04-10 21:18
> Well, I've just got that email too, also I've signed in letter. Does it means they're using that letter as list of emails to spam into?
> Actually, I've got it twice (one @ April, 7 and one just now). Should we mark them as spam or something?

Yes, he's been extracting the emails from this repo and the other letter. Mark it as spam and ignore, please.

**Comment by 6r1d** [comment] 2021-04-10 22:10
> One idea I had was reading what he had to say.

Chris, if you have any contacts with the person, can you explain that the method is a problem here, because mass-emails are inconvenient, people are not happy and the person sending those is ruining their reputation by doing that?
People do complain, so while an apology for the spam is not required, it will help the cause.

If there will be no research, no claims being checked and only "agree with what I'm telling you" or "disagree", not many will be interested. GitHub issues really help that.

Yes, I can read those emails, but in that case, I'll have to pour my time into research.
More often than not, others do it more effeciently and earlier, and this voting method doesn't allow that.

**Comment by aleksejrs** [comment] 2021-04-11 00:19
> ![Screenshot_2021-04-10 (5) Spam alsw protonmail com ProtonMail](https://user-images.githubusercontent.com/12746779/114284683-32288480-9a41-11eb-9106-cfc1dfa3c70f.png)

No matter who wrote that, "Aleksandra Fedorova" is the name of a Fedora person who against RMS and dpocock. Of course her e-mail address is different.

**Comment by alexpreynolds** [comment] 2021-04-11 01:15
Which group at Cornell provides CIVS with resources to operate? (Networking, server space, etc.) 

Is it affiliated with a particular academic department, or a side project by someone in IT, that sort of thing.

If CIVS cannot control its service, maybe it is time to have a talk with higher-ups and look into what it is being used for.

**Comment by ohsix** [comment] 2021-04-11 02:26
> Malignant narcissists commonly bait and smear their targets with impunity to the point that their enraged target will react and then that reaction is socialized as the justification for the targeting.

are you inventing a anonymous (but countably large) group of malignant narcissists to explain what you have right in front of you?

**Comment by graahnul-grom** [comment] 2021-04-11 02:32
So far, I've got 4 emails from civs@cornell.edu,
the last one arrived just today:

- Poll: Galia Mancheva and Susanne Eiswirt support letter
- Poll: Holocaust Memorial today, Debian defending Nazis, Say No
- Poll: Molly / Stallman role reversal puzzle
- Poll: Red Hat: justice must be equal

**Comment by cmpunches** [comment] 2021-04-11 02:41
> > Malignant narcissists commonly bait and smear their targets with impunity to the point that their enraged target will react and then that reaction is socialized as the justification for the targeting.
> 
> are you inventing a[n] anonymous (but countably large) group of malignant narcissists to explain what you have right in front of you?

No, that was not what was said or implied; it was the argument you created on my behalf when the original argument was not convenient for a narrative you would like to see painted, Josh.

As I was discussing, I am already familiar with your antics, @ohsix.  These tricks will not work on me in mediums that you do not control access to.  This is where you try to publicly humiliate me for calling you out.  I am ready for it.

But for the readers, these people are neither invented nor are their modes of operation unique -- there's a common pattern of behaviour in all of those campaigns and they tie back to cluster-B personality disorders and some of their common patterns.  I encourage anyone observing these events to educate themselves on NPD specifically and the volumes of reading available on the "flying monkey" roles that exist in those types of campaigns.  I view most of Daniel's behaviour so far as trauma response after being caught up in one of these.  I've seen a few of them over the years, and have even successfully fought a couple in more unregulated spaces.

The solution when a narcissist or their flying monkeys directly engage is to ignore them or shut them down completely by disarming them.  As for Daniel and people like Daniel,  his responses are, in my opinion, trauma responses that will only be aggravated by ignoring or trying to "punish away".  I think the way to stop this kind of thing is to help the guy and just listen to what he's trying to say.

**Comment by yhaenggi** [comment] 2021-04-11 07:04
> One idea I had was reading what he had to say.

No, never read/respond to spammers. All it will do, is teach them that its OK and efficient to spam people.

**Comment by Weilbyte** [comment] 2021-04-11 07:45
@graahnul-grom I have signed the other letter and still received these same ones, and one extra that appears to be directed at signers of the open letter only (titled "Poll: Removing your email from Molly's Open Letter"). 

You can add your email to the poll service's blacklist at https://civs1.civs.us/cgi-bin/mail_mgmt.pl, which should prevent further spam.

**Comment by cmpunches** [comment] 2021-04-11 08:04
> I have signed the other letter

*blocked*

**Comment by cmpunches** [comment] 2021-04-11 08:10
Can we close out this thread?  The deplorables are starting to group in.

**Comment by 6r1d** [comment] 2021-04-11 08:35
The sheer size of this topic shows how much attention spam gets. :/
I really wish Daniel had changed his methods and was helpful, but we have what we have, and I guess we reinforce that.

**Comment by cmpunches** [comment] 2021-04-11 08:43
> The sheer size of this topic shows how much attention spam gets. :/

@6r1d Ya know, I was just thinking the same thing.  I have 2,853 unread emails on my business account and 79,997 unread emails on my old personal account I abandoned for that one, and 99% of it is spam.  After a while it's just a daily read to catch up and my brain filters out most of it as I go clicking.

**Comment by ohsix** [comment] 2021-04-14 03:44
> But for the readers, these people are neither invented nor are their modes of operation unique -- there're common patterns in all of those campaigns and they tie back to cluster-B personality disorders and the behavioural patterns associated with those disorders. I encourage anyone observing these events to educate themselves on NPD specifically and the volumes of reading available on the "flying monkey" roles and interactional dynamics, and motivators that exist in those types of campaigns. I view most of Daniel's behaviour so far as trauma response after being caught up in one of these. I've seen a few of them over the years, and have even successfully fought a couple in more unregulated spaces.
> 
> The solution when a narcissist or their flying monkeys directly engage is to ignore them or shut them down completely by disarming them, or "growing thorns" when "grey rock" isn't going to work. As for Daniel and people like Daniel, his responses are, in my opinion, trauma responses that will only be aggravated by ignoring or trying to "punish away". I think the way to stop this kind of thing is to help the guy and just listen to what he's trying to say. That's not purely altruistic in motive but strategic -- if his only means of outlet is through methods like that instead of candid discussion, then his expression of it and attempts to address it will be through those means by necessity. I think it's important to create opportunities for resolution.
> 
> I'll also say that this is probably not the venue to discuss helping him out since it's not particularly on topic. The spam should be addressed.

didn't even read. hope it took a long time to write
